import { chromium } from '/opt/node22/lib/node_modules/playwright/index.mjs';
const out = process.env.SHOTS || '/tmp/shots';
const b = await chromium.launch({ executablePath: '/opt/pw-browsers/chromium-1194/chrome-linux/chrome', args: ['--no-sandbox'] });
const p = await b.newPage({ viewport: { width: 1280, height: 720 } });
const errs = []; p.on('console', m => { if (m.type() === 'error') errs.push(m.text()); }); p.on('pageerror', e => errs.push('PAGEERROR ' + e.message));
await p.goto('http://localhost:3000/'); await p.waitForTimeout(1500);
const click = (sel, text) => p.evaluate(([sel, text]) => { const e = [...document.querySelectorAll(sel)].find(x => x.textContent.trim().toUpperCase().includes(text)); if (!e) throw new Error('no ' + text); e.click(); }, [sel, text]);
const shot = async n => { await p.waitForTimeout(700); await p.screenshot({ path: `${out}/ui-${n}.png` }); };
const home = async () => { await p.evaluate(() => { KL.toMenu(); }); await p.waitForTimeout(500); };
await p.evaluate(() => { const s = JSON.parse(localStorage.getItem('killlap.v1') || '{}'); s.cash = 60000; localStorage.setItem('killlap.v1', JSON.stringify(s)); }); await p.reload(); await p.waitForTimeout(1200);
await click('.menu .btn', 'GARAGE'); await shot('garage');
await click('.ccard', 'REAPER'); await shot('garage-reaper');
await click('.btn', 'BUY'); await p.waitForTimeout(300); await click('.btn.mini', '$'); await shot('garage-bought');
await home(); await click('.menu .btn', 'CAREER'); await shot('career'); await click('.scard', 'ROOKIE'); await shot('series');
await home(); await click('.menu .btn', 'LEADERBOARDS'); await shot('boards');
await home(); await click('.menu .btn', 'SETTINGS'); await shot('settings');
await click('.btn', 'CONTROLS'); await shot('controls');
await home(); await click('.btn', 'ACHIEVEMENTS'); await shot('ach');
// editor
await home(); await click('.menu .btn', 'MAP EDITOR'); await p.waitForTimeout(800); await shot('editor');
const box = await p.evaluate(() => { const r = document.getElementById('edcv').getBoundingClientRect(); return [r.width, r.height]; });
await p.mouse.click(box[0] * 0.5, box[1] * 0.12); await p.waitForTimeout(200);
await p.mouse.click(box[0] * 0.3, box[1] * 0.12); await p.waitForTimeout(200);
await click('.edbar .btn', 'SCENERY'); await p.mouse.click(box[0] * 0.2, box[1] * 0.5); await p.waitForTimeout(200); await click('.edbar .btn', 'PICKUPS'); await p.mouse.click(box[0] * 0.45, box[1] * 0.6); await shot('editor2');
console.log('editor pts', await p.evaluate(() => window.KL && 'ok'));
await p.keyboard.press('KeyT'); await p.waitForTimeout(4500); await p.keyboard.down('KeyW'); await p.waitForTimeout(2500); await p.screenshot({ path: out + '/ui-testdrive.png' });
console.log('state', await p.evaluate(() => KL.state + ' ' + (KL.game ? KL.game.mode + ' ' + KL.game.T.name : '')));
await p.keyboard.up('KeyW'); await p.keyboard.press('Escape'); await p.waitForTimeout(600); await shot('pause');
await click('.btn', 'QUIT'); await p.waitForTimeout(1200); console.log('after quit', await p.evaluate(() => KL.state)); await p.screenshot({ path: out + '/ui-back-editor.png' });
console.log(errs.length ? errs.slice(0, 10).join('\n') : 'no errors'); await b.close();
